name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.2.3)"
        required: true
      description:
        description: "Description"
        required: false
        default: ""

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - run: |
          [[ "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]] || \
          (echo "Version must start with 'v' and match 'v<major>.<minor>.<patch>'" && exit 1)
      - uses: ./.github/actions/setup-node
        with:
          fetch-depth: 0
          registry-url: https://registry.npmjs.org/
          ref: ${{ github.ref }}
      - run: |
          pnpm run build
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          NPM_VERSION="${GITHUB_VERSION#v}"
          pnpm version "$NPM_VERSION" --allow-same-version
        env:
          GITHUB_VERSION: ${{ github.event.inputs.version }}

      - name: Publish to npm
        run: |
          pnpm publish --provenance --access public
          git push origin HEAD --follow-tags

      - name: Publish to github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
  
  image:
    needs: release
    permissions:
      packages: write
      id-token: write
    uses: ./.github/workflows/image.yml
    secrets: inherit
